import {renderPortalHome,renderPortalDetail,detailTitles} from './dist/portal-server.mjs';
import {serviceView} from './public/service.js';
import {faqView,productCardsView,sampleProducts} from './public/shared.js';
import http from 'node:http';
import { readFile, stat } from 'node:fs/promises';
import { createReadStream } from 'node:fs';
import { gzip } from 'node:zlib';
import { promisify } from 'node:util';
import { DatabaseSync } from 'node:sqlite';
import { randomBytes, scryptSync, timingSafeEqual, createHash } from 'node:crypto';
import { mkdirSync, readFileSync, writeFileSync, existsSync } from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const ROOT = path.dirname(fileURLToPath(import.meta.url));
try { process.loadEnvFile(path.join(ROOT, '.env')); } catch (error) { if (error.code !== 'ENOENT') throw error; }
const DATA = process.env.DATA_DIR || path.join(ROOT, 'data');
mkdirSync(DATA, { recursive: true });
const db = new DatabaseSync(path.join(DATA, 'boxanh.sqlite'));
db.exec('PRAGMA busy_timeout=5000;');
db.exec(`PRAGMA journal_mode=WAL; PRAGMA foreign_keys=ON;
CREATE TABLE IF NOT EXISTS settings (key TEXT PRIMARY KEY, value TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS bookings (id INTEGER PRIMARY KEY, code TEXT UNIQUE NOT NULL, request_id TEXT UNIQUE NOT NULL, phone TEXT NOT NULL, name TEXT NOT NULL, payload TEXT NOT NULL, estimate INTEGER NOT NULL, status TEXT NOT NULL DEFAULT 'requested', final_quote INTEGER, buyback_credit INTEGER NOT NULL DEFAULT 0, note TEXT NOT NULL DEFAULT '', created_at TEXT NOT NULL, updated_at TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS events (id INTEGER PRIMARY KEY, booking_id INTEGER NOT NULL REFERENCES bookings(id), status TEXT NOT NULL, note TEXT NOT NULL, created_at TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS goods (id INTEGER PRIMARY KEY, code TEXT UNIQUE NOT NULL, request_id TEXT UNIQUE NOT NULL, phone TEXT NOT NULL, name TEXT NOT NULL, category TEXT NOT NULL, mode TEXT NOT NULL, description TEXT NOT NULL, condition TEXT NOT NULL, booking_code TEXT, status TEXT NOT NULL DEFAULT 'received', valuation INTEGER, payout INTEGER, note TEXT NOT NULL DEFAULT '', created_at TEXT NOT NULL, updated_at TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS photos (id TEXT PRIMARY KEY, kind TEXT NOT NULL, record_id INTEGER NOT NULL, mime TEXT NOT NULL, data BLOB NOT NULL);
CREATE TABLE IF NOT EXISTS products (id INTEGER PRIMARY KEY, name TEXT NOT NULL, category TEXT NOT NULL, price INTEGER NOT NULL, description TEXT NOT NULL, image TEXT NOT NULL, condition TEXT NOT NULL, available INTEGER NOT NULL DEFAULT 1);
CREATE TABLE IF NOT EXISTS interests (id INTEGER PRIMARY KEY, code TEXT UNIQUE NOT NULL, request_id TEXT UNIQUE NOT NULL, product_id INTEGER NOT NULL REFERENCES products(id), phone TEXT NOT NULL, name TEXT NOT NULL, note TEXT NOT NULL DEFAULT '', status TEXT NOT NULL DEFAULT 'received', created_at TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS inventory (id INTEGER PRIMARY KEY CHECK(id=1), total INTEGER NOT NULL DEFAULT 0, cleaning INTEGER NOT NULL DEFAULT 0, retired INTEGER NOT NULL DEFAULT 0);
CREATE TABLE IF NOT EXISTS allocations (booking_id INTEGER PRIMARY KEY REFERENCES bookings(id), boxes INTEGER NOT NULL, returned INTEGER NOT NULL DEFAULT 0);
CREATE TABLE IF NOT EXISTS sessions (token_hash TEXT PRIMARY KEY, expires INTEGER NOT NULL);
CREATE TABLE IF NOT EXISTS audit (id INTEGER PRIMARY KEY, action TEXT NOT NULL, record_id TEXT NOT NULL, detail TEXT NOT NULL, created_at TEXT NOT NULL);
INSERT OR IGNORE INTO inventory(id,total) VALUES(1,0);`);
// Additive, versioned local migrations; never discard existing customer records.
if(db.prepare('PRAGMA user_version').get().user_version<1){transaction(()=>{
  db.exec('ALTER TABLE allocations ADD COLUMN delivered INTEGER NOT NULL DEFAULT 0');
  db.exec('ALTER TABLE goods ADD COLUMN service_credit INTEGER NOT NULL DEFAULT 0');
  db.exec('ALTER TABLE products ADD COLUMN goods_id INTEGER REFERENCES goods(id)');
  db.exec('PRAGMA user_version=1');
});}
db.exec(`CREATE TABLE IF NOT EXISTS issues (id INTEGER PRIMARY KEY, code TEXT UNIQUE NOT NULL, request_id TEXT UNIQUE NOT NULL, booking_code TEXT NOT NULL, phone TEXT NOT NULL, type TEXT NOT NULL, box_id TEXT NOT NULL DEFAULT '', seal_id TEXT NOT NULL DEFAULT '', description TEXT NOT NULL, status TEXT NOT NULL DEFAULT 'received', note TEXT NOT NULL DEFAULT '', created_at TEXT NOT NULL, updated_at TEXT NOT NULL);`);
const defaults={brand:'BOXANH',area:'Vinh, Nghệ An',phone:'0332357455',email:'',priceMode:'reference',bookingEnabled:true,smallBase:350000,fullBase:500000,boxBase:100000,boxUnit:10000,distanceUnit:18000,stairsUnit:25000,bulkyUnit:50000,packingFee:100000,rentalDays:5,extraBoxDay:5000};
if (!db.prepare('SELECT value FROM settings WHERE key=?').get('config')) db.prepare('INSERT INTO settings VALUES(?,?)').run('config',JSON.stringify(defaults));
function config(){return {...defaults,...JSON.parse(db.prepare('SELECT value FROM settings WHERE key=?').get('config').value)};}
function audit(action,id,detail){db.prepare('INSERT INTO audit(action,record_id,detail,created_at) VALUES(?,?,?,?)').run(action,String(id),JSON.stringify(detail),new Date().toISOString());}
const secretPath=path.join(DATA,'admin-auth.json');
let adminAuth;
if(process.env.NODE_ENV==='production'&&!process.env.ADMIN_PASSWORD)throw new Error('Set ADMIN_PASSWORD for production');
if(process.env.ADMIN_PASSWORD){
  if(process.env.ADMIN_PASSWORD.length<12)throw new Error('ADMIN_PASSWORD must have at least 12 characters');
  const salt=randomBytes(16).toString('hex');adminAuth={salt,hash:scryptSync(process.env.ADMIN_PASSWORD,salt,64).toString('hex')};
}else if(existsSync(secretPath)){adminAuth=JSON.parse(readFileSync(secretPath,'utf8'));}
else{
  if(process.env.NODE_ENV==='production')throw new Error('Set ADMIN_PASSWORD for production');
  const password=randomBytes(18).toString('base64url');const salt=randomBytes(16).toString('hex');
  adminAuth={salt,hash:scryptSync(password,salt,64).toString('hex')};
  writeFileSync(secretPath,JSON.stringify(adminAuth),{mode:0o600});
  writeFileSync(path.join(DATA,'admin-access.txt'),`BOXANH — truy cập quản trị trên máy này\nĐịa chỉ: /quan-tri\nMật khẩu: ${password}\n\nKhông đưa tệp này lên website, gửi cho khách hoặc đưa vào kho mã công khai.\nKhi triển khai hosting, đặt ADMIN_PASSWORD dài tối thiểu 12 ký tự trong biến môi trường.\n`,{mode:0o600});
}
const statuses=['requested','surveyed','quoted','confirmed','boxes_delivered','moving','arrived','boxes_collected','servicing','checked','completed','cancelled'];
function bookingSteps(service){if(['cleaning','handover'].includes(service))return ['requested','surveyed','quoted','confirmed','servicing','checked','completed'];return service==='boxes'?statuses.filter(s=>!['moving','arrived','servicing','checked','cancelled'].includes(s)):statuses.filter(s=>!['servicing','checked','cancelled'].includes(s));}
const statusLabels={requested:'Đã nhận yêu cầu',surveyed:'Đã khảo sát',quoted:'Đã gửi báo giá',confirmed:'Đã xác nhận lịch',boxes_delivered:'Đã giao hộp',moving:'Đang vận chuyển',arrived:'Đã giao đồ',boxes_collected:'Đã thu hồi hộp',servicing:'Đang thực hiện dịch vụ',checked:'Đã kiểm tra & bàn giao',completed:'Hoàn tất',cancelled:'Đã hủy'};
const goodsStatuses=['received','reviewing','offered','accepted','collected','listed','sold','paid','completed','rejected'];
const goodsLabels={received:'Đã nhận thông tin',reviewing:'Đang thẩm định',offered:'Đã gửi định giá',accepted:'Khách đã đồng ý',collected:'Đã tiếp nhận đồ',listed:'Đang ký gửi',sold:'Đã bán',paid:'Đã thanh toán',completed:'Đã chuyển đến đầu ra xác nhận',rejected:'Chưa phù hợp'};
function goodsSteps(mode){return mode==='consign'?['received','reviewing','offered','accepted','collected','listed','sold','paid']:mode==='buyback'?['received','reviewing','offered','accepted','collected','paid']:['received','reviewing','accepted','collected','completed'];}
db.prepare('DELETE FROM sessions').run();
const mimeTypes={'.html':'text/html; charset=utf-8','.css':'text/css; charset=utf-8','.js':'text/javascript; charset=utf-8','.txt':'text/plain; charset=utf-8','.svg':'image/svg+xml','.jpg':'image/jpeg','.jpeg':'image/jpeg','.png':'image/png','.webp':'image/webp','.woff2':'font/woff2','.glb':'model/gltf-binary','.wasm':'application/wasm','.mp4':'video/mp4','.mp3':'audio/mpeg','.wav':'audio/wav','.vtt':'text/vtt; charset=utf-8'};
const limits=new Map();
function rate(req,key,max=30){const ip=req.socket.remoteAddress||'unknown',k=ip+':'+key,t=Date.now();let v=limits.get(k);if(!v||t-v.start>600000)v={start:t,count:0};v.count++;limits.set(k,v);if(v.count>max)fail(429,'Bạn thao tác hơi nhanh. Vui lòng thử lại sau ít phút.');}
const cleanup=setInterval(()=>{const cutoff=Date.now()-600000;for(const [k,v] of limits)if(v.start<cutoff)limits.delete(k);db.prepare('DELETE FROM sessions WHERE expires<?').run(Date.now());},600000);cleanup.unref();
function fail(status,message){const e=new Error(message);e.status=status;throw e;}
function textValue(value,label,max=500,required=true){if(typeof value!=='string') {if(!required&&value===undefined)return '';fail(400,`Vui lòng nhập ${label}.`);}const s=value.trim();if((required&&!s)||s.length>max)fail(400,`${label} chưa hợp lệ.`);return s;}
function phoneValue(value){let p=textValue(value,'số điện thoại',25).replace(/[\s.()-]/g,'');if(p.startsWith('+84'))p='0'+p.slice(3);if(!/^0[35789]\d{8}$/.test(p))fail(400,'Số điện thoại Việt Nam cần có 10 chữ số.');return p;}
function intValue(value,label,min,max){if(!Number.isInteger(value)||value<min||value>max)fail(400,`${label} cần nằm trong khoảng ${min}–${max}.`);return value;}
function enumValue(value,allowed,label){if(!allowed.includes(value))fail(400,`${label} chưa hợp lệ.`);return value;}
function requestId(value){return textValue(value,'mã yêu cầu',80);}
function today(){return new Date(Date.now()+7*3600000).toISOString().slice(0,10);}
function dateValue(value){const v=textValue(value,'ngày chuyển',10);if(!/^\d{4}-\d{2}-\d{2}$/.test(v)||Number.isNaN(Date.parse(v))||new Date(v).toISOString().slice(0,10)!==v||v<today()||v>new Date(Date.now()+366*86400000).toISOString().slice(0,10))fail(400,'Ngày chuyển cần từ hôm nay đến 12 tháng tới.');return v;}
function code(prefix){return prefix+'-'+randomBytes(5).toString('hex').toUpperCase();}
function estimate(input){const c=config();const service=enumValue(input.service,['small','full','boxes','cleaning','handover'],'dịch vụ');if(['cleaning','handover'].includes(service))return {service,boxes:0,distance:0,originFloor:0,destinationFloor:0,bulky:0,lines:[],total:0,rentalDays:0,needsSurvey:true,priceMode:c.priceMode};const boxes=intValue(input.boxes??10,'số hộp',1,60);const distance=intValue(input.distance??5,'quãng đường',1,80);const originFloor=intValue(input.originFloor??0,'tầng nơi đi',0,15);const destinationFloor=intValue(input.destinationFloor??0,'tầng nơi đến',0,15);const bulky=intValue(input.bulky??0,'số món cồng kềnh',0,30);const lines=[];let base=service==='small'?c.smallBase:service==='full'?c.fullBase:c.boxBase;
  for(const key of ['originElevator','destinationElevator','packing'])if(input[key]!==undefined&&typeof input[key]!=='boolean')fail(400,'Thông tin thang máy / đóng gói chưa hợp lệ.');
  lines.push({label:service==='boxes'?'Giao và thu hồi hộp':'Phí gói cơ bản (5 km đầu)',amount:base});
  if(service==='boxes')lines.push({label:`${boxes} hộp / ${c.rentalDays} ngày`,amount:boxes*c.boxUnit});
  else {if(boxes>10)lines.push({label:`${boxes-10} hộp bổ sung`,amount:(boxes-10)*c.boxUnit});if(distance>5)lines.push({label:`Quãng đường thêm ${distance-5} km`,amount:(distance-5)*c.distanceUnit});const stairs=(input.originElevator?0:originFloor)+(input.destinationElevator?0:destinationFloor);if(stairs)lines.push({label:`Bưng bê cầu thang (${stairs} tầng)`,amount:stairs*c.stairsUnit});if(bulky)lines.push({label:`${bulky} món cồng kềnh`,amount:bulky*c.bulkyUnit});if(input.packing&&service!=='full')lines.push({label:'Hỗ trợ đóng gói',amount:c.packingFee});}
  return {service,boxes,distance,originFloor,destinationFloor,bulky,lines,total:lines.reduce((n,l)=>n+l.amount,0),rentalDays:c.rentalDays,priceMode:c.priceMode};
}
function parsePhotos(photos){if(photos===undefined)return [];if(!Array.isArray(photos)||photos.length>4)fail(400,'Tối đa 4 ảnh.');return photos.map(p=>{if(typeof p?.data!=='string'||p.data.length>3000000)fail(400,'Mỗi ảnh cần nhỏ hơn 2 MB.');const match=p.data.match(/^data:(image\/(?:jpeg|png|webp));base64,([A-Za-z0-9+/=]+)$/);if(!match)fail(400,'Ảnh cần ở định dạng JPG, PNG hoặc WebP.');const data=Buffer.from(match[2],'base64');if(data.length>2*1024*1024)fail(400,'Ảnh vượt quá 2 MB.');const mime=match[1];if((mime==='image/jpeg'&&!(data[0]===255&&data[1]===216&&data[2]===255))||(mime==='image/png'&&data.subarray(0,8).toString('hex')!=='89504e470d0a1a0a')||(mime==='image/webp'&&!(data.subarray(0,4).toString()==='RIFF'&&data.subarray(8,12).toString()==='WEBP')))fail(400,'Nội dung tệp không phải ảnh hợp lệ.');return {mime,data};});}
function savePhotos(photos,kind,id){for(const photo of photos)db.prepare('INSERT INTO photos VALUES(?,?,?,?,?)').run(randomBytes(16).toString('hex'),kind,id,photo.mime,photo.data);}
function photoList(kind,id){return db.prepare('SELECT id,mime FROM photos WHERE kind=? AND record_id=?').all(kind,id).map(p=>({id:p.id,url:'/api/admin/photos/'+p.id}));}
async function body(req){if(!/^application\/json\b/i.test(req.headers['content-type']||''))fail(415,'Yêu cầu cần là JSON.');let size=0;const chunks=[];for await(const chunk of req){size+=chunk.length;if(size>12*1024*1024)fail(413,'Dữ liệu quá lớn. Vui lòng giảm dung lượng ảnh.');chunks.push(chunk);}try {return JSON.parse(Buffer.concat(chunks).toString());}catch{fail(400,'Dữ liệu chưa hợp lệ.');}}
function secureHeaders(res){res.setHeader('X-Content-Type-Options','nosniff');res.setHeader('Referrer-Policy','same-origin');res.setHeader('X-Frame-Options','DENY');res.setHeader('Permissions-Policy','camera=(), microphone=(), geolocation=()');res.setHeader('Content-Security-Policy',"default-src 'self'; script-src 'self' 'wasm-unsafe-eval'; worker-src 'self' blob:; style-src 'self' https://fonts.googleapis.com; font-src 'self' https://fonts.gstatic.com; img-src 'self' data: blob: https://images.unsplash.com; connect-src 'self'; frame-ancestors 'none'; base-uri 'self'; form-action 'self'");}
function json(res,value,status=200){res.writeHead(status,{'Content-Type':'application/json; charset=utf-8','Cache-Control':'no-store'});res.end(JSON.stringify(value));}
function admin(req){const cookie=(req.headers.cookie||'').split(';').map(s=>s.trim()).find(s=>s.startsWith('boxanh_session='));const token=cookie?.slice(15);if(!token)fail(401,'Vui lòng đăng nhập quản trị.');const hash=createHash('sha256').update(token).digest('hex');if(!db.prepare('SELECT token_hash FROM sessions WHERE token_hash=? AND expires>?').get(hash,Date.now()))fail(401,'Phiên quản trị đã hết hạn.');return hash;}
function allowedPublicClient(req){return !!process.env.PUBLIC_CLIENT_ORIGIN&&req.headers.origin===process.env.PUBLIC_CLIENT_ORIGIN&&req.url.startsWith('/api/')&&!req.url.startsWith('/api/admin/');}
function sameOrigin(req){if(allowedPublicClient(req))return;const origin=req.headers.origin;if(origin){let host;try{host=new URL(origin).host;}catch{fail(403,'Nguồn yêu cầu chưa hợp lệ.');}if(host!==req.headers.host)fail(403,'Nguồn yêu cầu chưa hợp lệ.');}if(req.headers['sec-fetch-site']==='cross-site')fail(403,'Nguồn yêu cầu chưa hợp lệ.');}
function consent(input){if(input.consent!==true)fail(400,'Cần đồng ý xử lý thông tin để tiếp nhận yêu cầu.');if(input.website)fail(400,'Yêu cầu chưa hợp lệ.');}
function transaction(fn){db.exec('BEGIN IMMEDIATE');try{const result=fn();db.exec('COMMIT');return result;}catch(e){db.exec('ROLLBACK');throw e;}}
function inventory(){const inv=db.prepare('SELECT * FROM inventory WHERE id=1').get();const allocated=db.prepare('SELECT COALESCE(SUM(boxes-returned),0) AS n FROM allocations WHERE delivered=1').get().n,reserved=db.prepare('SELECT COALESCE(SUM(boxes),0) AS n FROM allocations WHERE delivered=0').get().n;return {...inv,allocated,reserved,available:inv.total-inv.cleaning-inv.retired-allocated-reserved};}
function publicTracking(record,kind){if(kind==='booking'){const p=JSON.parse(record.payload);return {kind,code:record.code,name:record.name.split(' ').slice(-1)[0],status:record.status,label:statusLabels[record.status],date:p.date,slot:p.slot,service:p.service,boxes:p.boxes,estimate:record.estimate,finalQuote:record.final_quote,credit:record.buyback_credit,createdAt:record.created_at,events:db.prepare('SELECT status,note,created_at FROM events WHERE booking_id=? ORDER BY id').all(record.id).map(e=>({...e,label:statusLabels[e.status]})),steps:bookingSteps(p.service).map(s=>({status:s,label:statusLabels[s]}))};}return {kind,code:record.code,status:record.status,label:goodsLabels[record.status],mode:record.mode,category:record.category,valuation:record.valuation,payout:record.payout,credit:record.service_credit,createdAt:record.created_at};}
async function api(req,res,url){const route=url.pathname,method=req.method;
  if(method!=='GET')sameOrigin(req);
  if(method==='GET'&&route==='/api/config')return json(res,{...config(),publicPreview:process.env.PUBLIC_PREVIEW==='1'});
  if(method==='GET'&&route==='/api/products')return json(res,db.prepare('SELECT * FROM products WHERE available=1 ORDER BY id DESC').all());
  if(method==='GET'&&route.startsWith('/api/product-photos/')){const photo=db.prepare("SELECT mime,data FROM photos WHERE id=? AND kind='product'").get(route.split('/').at(-1));if(!photo)fail(404,'Không tìm thấy ảnh món đồ.');res.writeHead(200,{'Content-Type':photo.mime,'Cache-Control':'public, max-age=3600'});return res.end(Buffer.from(photo.data));}
  if(method==='POST'&&route==='/api/quote'){rate(req,'quote',150);return json(res,estimate(await body(req)));}
  if(method==='POST'&&route==='/api/bookings'){
    rate(req,'booking',20);const input=await body(req);consent(input);if(!config().bookingEnabled)fail(503,'BOXANH đang tạm ngưng nhận lịch mới. Vui lòng liên hệ qua điện thoại.');const rid=requestId(input.requestId),phone=phoneValue(input.phone);const existing=db.prepare('SELECT code,phone,estimate FROM bookings WHERE request_id=?').get(rid);if(existing){if(existing.phone!==phone)fail(409,'Mã yêu cầu đã được dùng.');return json(res,{code:existing.code,estimate:existing.estimate});}
    const quote=estimate(input),name=textValue(input.name,'họ tên',100),origin=textValue(input.origin,'địa chỉ lấy đồ',300),destination=textValue(input.destination,'địa chỉ giao đồ',300),date=dateValue(input.date),slot=enumValue(input.slot,['morning','afternoon','evening'],'khung giờ');
    const payload={...quote,roomArea:['cleaning','handover'].includes(quote.service)?intValue(Number(input.roomArea),'diện tích phòng',1,500):null,origin,destination,date,slot,originElevator:input.originElevator===true,destinationElevator:input.destinationElevator===true,packing:input.packing===true,surplusMode:enumValue(input.surplusMode||'none',['none','buyback','consign','recycle'],'hình thức xử lý đồ'),surplusDescription:textValue(input.surplusDescription||'','mô tả đồ cũ',1500,false),notes:textValue(input.notes||'','ghi chú',1500,false),consent:true,consentVersion:'2026-10-03'};const photos=parsePhotos(input.photos),now=new Date().toISOString(),ref=code('BX');
    if(payload.surplusMode!=='none'&&!payload.surplusDescription)fail(400,'Mô tả đồ không mang theo để BOXANH thẩm định.');
    transaction(()=>{const r=db.prepare('INSERT INTO bookings(code,request_id,phone,name,payload,estimate,created_at,updated_at) VALUES(?,?,?,?,?,?,?,?)').run(ref,rid,phone,name,JSON.stringify(payload),quote.total,now,now);db.prepare('INSERT INTO events(booking_id,status,note,created_at) VALUES(?,?,?,?)').run(r.lastInsertRowid,'requested','BOXANH đã tiếp nhận yêu cầu. Lịch sẽ được xác nhận sau khảo sát.',now);savePhotos(photos,'booking',Number(r.lastInsertRowid));if(payload.surplusMode!=='none'){const goodsCode=code('DG'),g=db.prepare('INSERT INTO goods(code,request_id,phone,name,category,mode,description,condition,booking_code,created_at,updated_at) VALUES(?,?,?,?,?,?,?,?,?,?,?)').run(goodsCode,rid+'-goods',phone,name,'other',payload.surplusMode,payload.surplusDescription,payload.surplusMode==='recycle'?'broken':'fair',ref,now,now);savePhotos(photos,'goods',Number(g.lastInsertRowid));audit('goods.created',goodsCode,{booking:ref});}audit('booking.created',ref,{service:quote.service});});return json(res,{code:ref,estimate:quote.total},201);
  }

  if(method==='POST'&&route==='/api/issues'){
    rate(req,'issue',20);const input=await body(req);consent(input);const rid=requestId(input.requestId),phone=phoneValue(input.phone),bookingCode=textValue(input.code,'mã đơn',30).toUpperCase();
    if(!db.prepare('SELECT id FROM bookings WHERE code=? AND phone=?').get(bookingCode,phone))fail(404,'Chưa tìm thấy đơn khớp mã và số điện thoại. Vui lòng kiểm tra hoặc gọi CSKH.');
    const existing=db.prepare('SELECT code,booking_code,phone FROM issues WHERE request_id=?').get(rid);if(existing){if(existing.phone!==phone||existing.booking_code!==bookingCode)fail(409,'Mã yêu cầu đã được dùng.');return json(res,{code:existing.code});}
    const type=enumValue(input.type,['missing','seal','damage','box','other'],'vấn đề'),description=textValue(input.description,'thông tin sự cố',2000),boxId=textValue(input.boxId||'','mã hộp',80,false),sealId=textValue(input.sealId||'','mã seal',80,false),photos=parsePhotos(input.photos),now=new Date().toISOString(),ref=code('SC');if(description.length<10)fail(400,'Mô tả sự cố cần ít nhất 10 ký tự.');
    transaction(()=>{const r=db.prepare('INSERT INTO issues(code,request_id,booking_code,phone,type,box_id,seal_id,description,created_at,updated_at) VALUES(?,?,?,?,?,?,?,?,?,?)').run(ref,rid,bookingCode,phone,type,boxId,sealId,description,now,now);savePhotos(photos,'issue',Number(r.lastInsertRowid));audit('issue.created',ref,{booking:bookingCode,type});});return json(res,{code:ref},201);
  }
  if(method==='POST'&&route==='/api/goods'){
    rate(req,'goods',20);const input=await body(req);consent(input);const rid=requestId(input.requestId),phone=phoneValue(input.phone);const existing=db.prepare('SELECT code,phone FROM goods WHERE request_id=?').get(rid);if(existing){if(existing.phone!==phone)fail(409,'Mã yêu cầu đã được dùng.');return json(res,{code:existing.code});}const name=textValue(input.name,'họ tên',100),category=enumValue(input.category,['furniture','electronics','books','clothing','other'],'nhóm đồ'),mode=enumValue(input.mode,['buyback','consign','recycle'],'hình thức'),condition=enumValue(input.condition,['good','fair','broken'],'tình trạng'),description=textValue(input.description,'mô tả đồ',2000),bookingCode=textValue(input.bookingCode||'','mã đơn liên quan',30,false).toUpperCase();
    if(mode!=='recycle'&&condition==='broken')fail(400,'Đồ hỏng cần chọn phân loại/thu gom.');if(bookingCode&&!db.prepare('SELECT id FROM bookings WHERE code=? AND phone=?').get(bookingCode,phone))fail(400,'Mã đơn chuyển trọ cần đúng và cùng số điện thoại.');const photos=parsePhotos(input.photos),now=new Date().toISOString(),ref=code('DG');transaction(()=>{const r=db.prepare('INSERT INTO goods(code,request_id,phone,name,category,mode,description,condition,booking_code,created_at,updated_at) VALUES(?,?,?,?,?,?,?,?,?,?,?)').run(ref,rid,phone,name,category,mode,description,condition,bookingCode||null,now,now);savePhotos(photos,'goods',Number(r.lastInsertRowid));audit('goods.created',ref,{mode});});return json(res,{code:ref},201);
  }
  if(method==='POST'&&route==='/api/interests'){
    rate(req,'interest',20);const input=await body(req);consent(input);const rid=requestId(input.requestId),phone=phoneValue(input.phone),name=textValue(input.name,'họ tên',100);const existing=db.prepare('SELECT code,phone FROM interests WHERE request_id=?').get(rid);if(existing){if(existing.phone!==phone)fail(409,'Mã yêu cầu đã được dùng.');return json(res,{code:existing.code});}const productId=intValue(input.productId,'món đồ',1,99999999),product=db.prepare('SELECT * FROM products WHERE id=? AND available=1').get(productId);if(!product)fail(409,'Món đồ hiện chưa còn khả dụng.');const ref=code('MH');db.prepare('INSERT INTO interests(code,request_id,product_id,phone,name,note,created_at) VALUES(?,?,?,?,?,?,?)').run(ref,rid,productId,phone,name,textValue(input.note||'','ghi chú',500,false),new Date().toISOString());audit('interest.created',ref,{});return json(res,{code:ref},201);
  }
  if(method==='POST'&&route==='/api/track'){
    rate(req,'track',30);const input=await body(req),ref=textValue(input.code,'mã yêu cầu',30).toUpperCase(),phone=phoneValue(input.phone);const record=db.prepare('SELECT * FROM bookings WHERE code=? AND phone=?').get(ref,phone);if(record)return json(res,publicTracking(record,'booking'));const goods=db.prepare('SELECT * FROM goods WHERE code=? AND phone=?').get(ref,phone);if(goods)return json(res,publicTracking(goods,'goods'));const interest=db.prepare('SELECT i.*,p.name AS product_name FROM interests i JOIN products p ON p.id=i.product_id WHERE i.code=? AND i.phone=?').get(ref,phone);if(interest)return json(res,{kind:'interest',code:ref,status:interest.status,product:interest.product_name,createdAt:interest.created_at});const issue=db.prepare('SELECT * FROM issues WHERE code=? AND phone=?').get(ref,phone);if(issue)return json(res,{kind:'issue',code:issue.code,bookingCode:issue.booking_code,status:issue.status,label:{received:'Đã tiếp nhận',reviewing:'Đang kiểm tra',resolved:'Đã ghi nhận kết quả'}[issue.status],note:issue.note});fail(404,'Chưa tìm thấy yêu cầu. Kiểm tra mã và số điện thoại đã đăng ký.');
  }
  if(method==='POST'&&route==='/api/admin/login'){
    rate(req,'login',8);const input=await body(req);const password=textValue(input.password,'mật khẩu',200);const hash=scryptSync(password,adminAuth.salt,64),expected=Buffer.from(adminAuth.hash,'hex');if(!timingSafeEqual(hash,expected))fail(401,'Mật khẩu chưa đúng.');const token=randomBytes(32).toString('base64url');db.prepare('INSERT INTO sessions VALUES(?,?)').run(createHash('sha256').update(token).digest('hex'),Date.now()+8*3600000);const secure=process.env.NODE_ENV==='production'?'; Secure':'';res.setHeader('Set-Cookie',`boxanh_session=${token}; HttpOnly; SameSite=Strict; Path=/; Max-Age=28800${secure}`);return json(res,{ok:true});
  }
  if(route.startsWith('/api/admin/')){
    const session=admin(req);
    if(method==='POST'&&/^\/api\/admin\/issues\/\d+$/.test(route)){const id=Number(route.split('/').at(-1)),record=db.prepare('SELECT * FROM issues WHERE id=?').get(id);if(!record)fail(404,'Không tìm thấy sự cố.');const input=await body(req),status=enumValue(input.status,['received','reviewing','resolved'],'trạng thái'),note=textValue(input.note||'','ghi nhận kiểm tra',2000,false);const steps=['received','reviewing','resolved'];if(status!==record.status&&steps[steps.indexOf(record.status)+1]!==status)fail(409,'Cập nhật lần lượt từ tiếp nhận đến kiểm tra và ghi nhận kết quả.');if(status==='resolved'&&!note)fail(400,'Ghi kết quả kiểm tra và phương án đã trao đổi trước khi hoàn tất.');db.prepare('UPDATE issues SET status=?,note=?,updated_at=? WHERE id=?').run(status,note,new Date().toISOString(),id);audit('issue.updated',record.code,{status});return json(res,{ok:true});}

    if(method==='POST'&&route==='/api/admin/logout'){db.prepare('DELETE FROM sessions WHERE token_hash=?').run(session);res.setHeader('Set-Cookie','boxanh_session=; HttpOnly; SameSite=Strict; Path=/; Max-Age=0');return json(res,{ok:true});}
    if(method==='GET'&&route==='/api/admin/dashboard'){const bookings=db.prepare('SELECT * FROM bookings ORDER BY id DESC LIMIT 500').all().map(b=>({...b,payload:JSON.parse(b.payload),photos:photoList('booking',b.id),allocation:db.prepare('SELECT * FROM allocations WHERE booking_id=?').get(b.id)||null,steps:bookingSteps(JSON.parse(b.payload).service)}));const goods=db.prepare('SELECT * FROM goods ORDER BY id DESC LIMIT 500').all().map(g=>({...g,photos:photoList('goods',g.id),steps:goodsSteps(g.mode)}));const interests=db.prepare('SELECT i.*,p.name AS product_name FROM interests i JOIN products p ON p.id=i.product_id ORDER BY i.id DESC LIMIT 500').all();return json(res,{bookings,goods,interests,products:db.prepare('SELECT * FROM products ORDER BY id DESC').all(),inventory:inventory(),config:config(),statuses,statusLabels,goodsStatuses,goodsLabels,issues:db.prepare('SELECT * FROM issues ORDER BY id DESC LIMIT 500').all().map(i=>({...i,photos:photoList('issue',i.id)})),audit:db.prepare('SELECT action,record_id,detail,created_at FROM audit ORDER BY id DESC LIMIT 80').all()});}
    if(method==='GET'&&route.startsWith('/api/admin/photos/')){const id=route.split('/').at(-1);const photo=db.prepare('SELECT mime,data FROM photos WHERE id=?').get(id);if(!photo)fail(404,'Ảnh không còn tồn tại.');res.writeHead(200,{'Content-Type':photo.mime,'Cache-Control':'private, no-store'});return res.end(Buffer.from(photo.data));}
    if(method==='POST'&&/^\/api\/admin\/bookings\/\d+$/.test(route)){
      const id=Number(route.split('/').at(-1)),record=db.prepare('SELECT * FROM bookings WHERE id=?').get(id);if(!record)fail(404,'Không tìm thấy đơn.');const input=await body(req),status=enumValue(input.status,statuses,'trạng thái'),note=textValue(input.note||'','ghi chú vận hành',1500,false);const finalQuote=input.finalQuote===null?null:intValue(input.finalQuote,'báo giá chốt',0,100000000);const now=new Date().toISOString();
      if(['quoted','confirmed','boxes_delivered','moving','arrived','boxes_collected','servicing','checked','completed'].includes(status)&&finalQuote===null)fail(400,'Cần chốt báo giá trước khi xác nhận lịch.');
      if(record.buyback_credit>0&&(finalQuote===null||finalQuote<record.buyback_credit))fail(400,'Báo giá không được thấp hơn phần thu mua đã phân bổ trừ phí.');
      const terminal=['cancelled','completed'].includes(record.status);if(terminal&&status!==record.status)fail(409,'Đơn đã kết thúc. Cần tạo yêu cầu mới thay vì đổi lại trạng thái.');
      const p=JSON.parse(record.payload),steps=bookingSteps(p.service);if(status!==record.status&&status!=='cancelled'&&steps[steps.indexOf(record.status)+1]!==status)fail(409,'Cần cập nhật lần lượt theo hành trình dịch vụ.');
      const bookingAlloc=db.prepare('SELECT * FROM allocations WHERE booking_id=?').get(id),goodReturn=intValue(input.goodReturn??0,'hộp tốt nhận thêm',0,60),damagedReturn=intValue(input.damagedReturn??0,'hộp hỏng nhận thêm',0,60),lost=intValue(input.lost??0,'hộp mất đối soát thêm',0,60),settled=goodReturn+damagedReturn+lost;
      if(settled&&(!bookingAlloc?.delivered||['confirmed','boxes_delivered','moving'].includes(status)&&p.service!=='boxes'))fail(409,'Chỉ kiểm đếm thu hồi sau giao đồ hoặc trong gói thuê hộp đã giao.');
      if(settled&&settled>bookingAlloc.boxes-bookingAlloc.returned)fail(409,'Số hộp đối soát vượt số đang giao.');
      if(lost&&!note)fail(400,'Ghi rõ thỏa thuận đối soát hộp mất trong ghi chú.');
      if(p.boxes>0&&['boxes_collected','completed'].includes(status)&&(!bookingAlloc?.delivered||bookingAlloc.returned+settled!==bookingAlloc.boxes))fail(409,'Cần kiểm đếm đủ hộp thu hồi hoặc đối soát hộp mất trước khi hoàn tất.');
      if(status==='cancelled'&&bookingAlloc?.delivered&&bookingAlloc.returned+settled<bookingAlloc.boxes)fail(409,'Cần đối soát hộp đã giao trước khi hủy.');
      transaction(()=>{if(status==='confirmed'&&!bookingAlloc&&p.boxes>0){if(inventory().available<p.boxes)fail(409,'Không đủ hộp sạch để giữ cho lịch này.');db.prepare('INSERT INTO allocations(booking_id,boxes) VALUES(?,?)').run(id,p.boxes);}if(status==='boxes_delivered'){if(!bookingAlloc)fail(409,'Cần giữ hộp khi xác nhận lịch.');db.prepare('UPDATE allocations SET delivered=1 WHERE booking_id=?').run(id);}if(settled){db.prepare('UPDATE allocations SET returned=returned+? WHERE booking_id=?').run(settled,id);db.prepare('UPDATE inventory SET cleaning=cleaning+?,retired=retired+? WHERE id=1').run(goodReturn,damagedReturn+lost);}if(status==='cancelled'&&bookingAlloc&&!bookingAlloc.delivered)db.prepare('DELETE FROM allocations WHERE booking_id=?').run(id);db.prepare('UPDATE bookings SET status=?,final_quote=?,note=?,updated_at=? WHERE id=?').run(status,finalQuote,note,now,id);if(status!==record.status)db.prepare('INSERT INTO events(booking_id,status,note,created_at) VALUES(?,?,?,?)').run(id,status,'Tiến độ được cập nhật bởi BOXANH.',now);audit('booking.updated',record.code,{status,finalQuote,goodReturn,damagedReturn,lost});});return json(res,{ok:true});
    }
    if(method==='POST'&&/^\/api\/admin\/goods\/\d+$/.test(route)){
      const id=Number(route.split('/').at(-1)),record=db.prepare('SELECT * FROM goods WHERE id=?').get(id);if(!record)fail(404,'Không tìm thấy đồ ký gửi.');const input=await body(req),status=enumValue(input.status,goodsStatuses,'trạng thái'),valuation=input.valuation===null?null:intValue(input.valuation,'định giá',0,100000000),payout=input.payout===null?null:intValue(input.payout,'tiền thanh toán',0,100000000),note=textValue(input.note||'','ghi chú',1500,false);if(record.mode==='consign'&&status==='paid'&&payout===null)fail(400,'Cần nhập tiền thanh toán sau khi bán.');if(record.mode==='buyback'&&['offered','accepted','collected','paid'].includes(status)&&valuation===null)fail(400,'Cần định giá thu mua trước khi khách đồng ý.');
      const steps=goodsSteps(record.mode),credit=intValue(input.credit??0,'giá trị trừ phí',0,100000000);if(status!==record.status&&!(status==='rejected'&&steps.indexOf(record.status)<steps.indexOf('collected'))&&steps[steps.indexOf(record.status)+1]!==status)fail(409,'Cần cập nhật lần lượt theo phương án tiếp nhận đồ.');
      if(['paid','completed','rejected'].includes(record.status)&&(status!==record.status||valuation!==record.valuation||payout!==record.payout||credit!==record.service_credit))fail(409,'Hồ sơ đã kết thúc đối soát; không sửa khoản đã thanh toán.');
      if(record.mode!=='buyback'&&credit)fail(400,'Chỉ thu mua được phân bổ trừ phí chuyển.');
      if(credit&&!record.booking_code)fail(400,'Chưa liên kết đơn để trừ phí.');
      if(credit){const linked=db.prepare('SELECT final_quote FROM bookings WHERE code=?').get(record.booking_code),other=db.prepare("SELECT COALESCE(SUM(service_credit),0) AS total FROM goods WHERE booking_code=? AND id<>? AND mode='buyback' AND status IN ('collected','paid')").get(record.booking_code,id).total;if(linked?.final_quote===null||!linked)fail(400,'Cần chốt giá dịch vụ trước khi phân bổ trừ phí.');if(credit+other>linked.final_quote)fail(400,'Tổng giá trị trừ phí không vượt phí dịch vụ đã chốt. Phần vượt cần trả trực tiếp.');}
      if((credit||(payout??0)>0)&&!['collected','paid'].includes(status)&&record.mode==='buyback')fail(400,'Chưa nhận đồ để ghi nhận giảm phí / thanh toán.');
      if(record.mode==='buyback'&&credit+(payout??0)>(valuation??0))fail(400,'Giảm phí cộng tiền trả trực tiếp không được vượt giá thu mua.');
      if(record.mode==='buyback'&&status==='paid'&&credit+(payout??0)!==valuation)fail(400,'Cần đối soát đủ giá thu mua bằng giảm phí và tiền trả trực tiếp.');
      if(record.mode==='consign'&&payout!==null&&!['sold','paid'].includes(status))fail(400,'Ký gửi chỉ ghi tiền sau khi bán.');
      if(record.mode==='recycle'&&(valuation!==null||payout!==null||credit))fail(400,'Phân loại/thu gom không có giá thu mua hoặc giảm phí.');
      if(record.mode==='recycle'&&status==='completed'&&!note)fail(400,'Ghi rõ đơn vị tiếp nhận và đầu ra đã xác nhận.');
      transaction(()=>{db.prepare('UPDATE goods SET status=?,valuation=?,payout=?,service_credit=?,note=?,updated_at=? WHERE id=?').run(status,valuation,payout,credit,note,new Date().toISOString(),id);if(record.booking_code){const total=db.prepare("SELECT COALESCE(SUM(service_credit),0) AS total FROM goods WHERE booking_code=? AND mode='buyback' AND status IN ('collected','paid')").get(record.booking_code).total;db.prepare('UPDATE bookings SET buyback_credit=? WHERE code=?').run(total,record.booking_code);}if(record.mode==='consign'&&['sold','paid','rejected'].includes(status))db.prepare('UPDATE products SET available=0 WHERE goods_id=?').run(id);audit('goods.updated',record.code,{status,valuation,payout,credit});});return json(res,{ok:true});
    }
    if(method==='POST'&&route==='/api/admin/config'){const input=await body(req),c=config();for(const key of ['smallBase','fullBase','boxBase','boxUnit','distanceUnit','stairsUnit','bulkyUnit','packingFee','extraBoxDay'])c[key]=intValue(input[key],key,0,10000000);c.rentalDays=intValue(input.rentalDays,'ngày thuê hộp',1,30);c.area=textValue(input.area,'khu vực',150);c.phone=phoneValue(input.phone);c.email=textValue(input.email||'','email',200,false);if(c.email&&!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(c.email))fail(400,'Email chưa hợp lệ.');c.priceMode=enumValue(input.priceMode,['reference','official'],'trạng thái bảng giá');c.bookingEnabled=input.bookingEnabled===true;db.prepare('UPDATE settings SET value=? WHERE key=?').run(JSON.stringify(c),'config');audit('config.updated','config',{});return json(res,{ok:true});}
    if(method==='POST'&&route==='/api/admin/inventory'){const input=await body(req),inv=inventory(),total=intValue(input.total,'tổng số hộp',0,100000),cleaning=intValue(input.cleaning,'hộp chờ vệ sinh',0,100000),retired=intValue(input.retired,'hộp ngừng sử dụng',0,100000);if(total<cleaning+retired+inv.allocated+inv.reserved)fail(409,'Tổng hộp phải đủ cho hộp đã giữ, đang giao, vệ sinh và ngừng sử dụng.');db.prepare('UPDATE inventory SET total=?,cleaning=?,retired=? WHERE id=1').run(total,cleaning,retired);audit('inventory.updated','1',{total,cleaning,retired});return json(res,{ok:true});}
    if(method==='POST'&&route==='/api/admin/products'){const input=await body(req),name=textValue(input.name,'tên món đồ',150),category=enumValue(input.category,['furniture','electronics','books','clothing','other'],'nhóm đồ'),price=intValue(input.price,'giá bán',0,100000000),description=textValue(input.description,'mô tả',2000),condition=textValue(input.condition,'tình trạng',100),image=textValue(input.image||'/assets/room.jpg','ảnh',500),photos=parsePhotos(input.photos),goodsId=input.goodsId?intValue(Number(input.goodsId),'hồ sơ đồ',1,999999999):null;if(photos.length!==1)fail(400,'Cần 1 ảnh thật của món đồ.');if(!/^\/assets\/[a-z0-9_.-]+\.(jpg|jpeg|png|webp)$/i.test(image)||!existsSync(path.join(ROOT,'public',image)))fail(400,'Chọn ảnh trong thư viện được cung cấp.');let source;if(goodsId){source=db.prepare('SELECT * FROM goods WHERE id=?').get(goodsId);if(!source||!['collected','listed','paid'].includes(source.status)||source.mode==='recycle'||source.mode==='consign'&&source.status==='paid')fail(400,'Hồ sơ cần đã tiếp nhận và còn được phép bán.');if(db.prepare('SELECT id FROM products WHERE goods_id=?').get(goodsId))fail(409,'Hồ sơ này đã có món đồ trong danh mục.');}transaction(()=>{const r=db.prepare('INSERT INTO products(name,category,price,description,image,condition,goods_id) VALUES(?,?,?,?,?,?,?)').run(name,category,price,description,image,condition,goodsId);const id=Number(r.lastInsertRowid);if(photos.length){const photoId=randomBytes(16).toString('hex');db.prepare('INSERT INTO photos VALUES(?,?,?,?,?)').run(photoId,'product',id,photos[0].mime,photos[0].data);db.prepare('UPDATE products SET image=? WHERE id=?').run('/api/product-photos/'+photoId,id);}if(source?.mode==='consign'&&source.status==='collected')db.prepare("UPDATE goods SET status='listed',updated_at=? WHERE id=?").run(new Date().toISOString(),goodsId);audit('product.created',id,{name,goodsId});});return json(res,{ok:true});}
    if(method==='POST'&&/^\/api\/admin\/products\/\d+$/.test(route)){const id=Number(route.split('/').at(-1)),input=await body(req),product=db.prepare('SELECT * FROM products WHERE id=?').get(id);if(!product)fail(404,'Không tìm thấy món đồ.');if(typeof input.available!=='boolean')fail(400,'Trạng thái hiển thị chưa hợp lệ.');if(input.available&&product.goods_id){const source=db.prepare('SELECT mode,status FROM goods WHERE id=?').get(product.goods_id);if(!source||source.mode==='consign'&&!['collected','listed'].includes(source.status)||source.mode==='buyback'&&!['collected','paid'].includes(source.status)||source.mode==='recycle')fail(409,'Hồ sơ nguồn đã bán hoặc không còn được phép hiển thị.');}db.prepare('UPDATE products SET available=? WHERE id=?').run(input.available?1:0,id);audit('product.availability',id,{available:input.available});return json(res,{ok:true});}
    if(method==='POST'&&/^\/api\/admin\/interests\/\d+$/.test(route)){const id=Number(route.split('/').at(-1)),input=await body(req),status=enumValue(input.status,['received','contacted','completed','cancelled'],'trạng thái');db.prepare('UPDATE interests SET status=? WHERE id=?').run(status,id);audit('interest.updated',id,{status});return json(res,{ok:true});}
    if(method==='GET'&&route==='/api/admin/export'){const rows=db.prepare('SELECT code,name,phone,status,estimate,final_quote,buyback_credit,created_at FROM bookings ORDER BY id DESC').all();function csv(v){let s=String(v??'');if(/^[=+\-@\t\r]/.test(s))s="'"+s;return '"'+s.replaceAll('"','""')+'"';}const head=['Mã đơn','Họ tên','Số điện thoại','Trạng thái','Giá dự kiến','Giá chốt','Giảm phí thu mua','Ngày tạo'];const csvText='\uFEFF'+[head,...rows.map(r=>Object.values(r))].map(row=>row.map(csv).join(',')).join('\r\n');res.writeHead(200,{'Content-Type':'text/csv; charset=utf-8','Content-Disposition':'attachment; filename="BOXANH-don-chuyen-tro.csv"','Cache-Control':'no-store'});return res.end(csvText);}
  }
  fail(404,'Chức năng không tồn tại.');
}
const compress=promisify(gzip),staticCache=new Map();
const pageMoney=n=>new Intl.NumberFormat('vi-VN',{style:'currency',currency:'VND',maximumFractionDigits:0}).format(n||0);
const pageEscape=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function renderPublicHTML(template,route,c){
 const ctx={config:c,money:pageMoney,esc:pageEscape,faq:()=>faqView({config:c,esc:pageEscape}),sampleProducts,productCards:(items,sample)=>productCardsView(items,sample,{config:c,money:pageMoney,esc:pageEscape,categories:{}})};
 const page=route==='/'?renderPortalHome(c):route==='/dich-vu'?serviceView(ctx):detailTitles[route]?renderPortalDetail(route,c):null;
 const pageTitles={'/':'BOXANH — Chuyển trọ Vinh, dọn phòng & bàn giao','/dich-vu':'Dịch vụ & giá tham khảo tại Vinh — BOXANH','/ho-tro':'CSKH & sự cố đồ đạc — BOXANH','/dat-lich':'Nhận báo giá dịch vụ — BOXANH'};
 let result=template.replace('<!--BOXANH_CONFIG-->',()=>'<script type="application/json" id="site-config">'+JSON.stringify(c).replaceAll('<','\\u003c')+'</script>');
 result=result.replace('<body data-route="/">','<body data-route="'+pageEscape(route)+'">');
 if(route!=='/')result=result.replace('data-service-masthead>','data-service-masthead hidden>');
 result=result.replace(/<title>[^<]*<\/title>/,()=>'<title>'+pageEscape(pageTitles[route]||(detailTitles[route]?detailTitles[route]+' — BOXANH':'BOXANH — Dịch vụ tại Vinh'))+'</title>');
 if(page)result=result.replace(/(<main id="main"[^>]*>)[\s\S]*?(<\/main>)/,(_,open,close)=>open+page+close);
 if(route!=='/'){result=result.replace('id="route-backbar" hidden','id="route-backbar"');result=result.replace('<span id="route-current">Dịch vụ</span>','<span id="route-current">'+pageEscape(detailTitles[route]||pageTitles[route]?.split(' —')[0]||'BOXANH')+'</span>');}
 if(c.publicPreview)result=result.replace('<a href="/quan-tri">Cổng vận hành</a>','');
 return result;
}
async function serveStatic(req,res,target){
 if(['.mp4','.mp3'].includes(path.extname(target))){
  const info=await stat(target),size=info.size,etag='"'+info.mtimeMs+'-'+size+'"',headers={'Content-Type':mimeTypes[path.extname(target)],'Accept-Ranges':'bytes','Cache-Control':'public, max-age=300',ETag:etag};
  if(req.headers['if-none-match']===etag&&!req.headers.range){res.writeHead(304,headers);return res.end();}
  let start=0,end=size-1,status=200;
  if(req.headers.range){const match=/^bytes=(\d*)-(\d*)$/.exec(req.headers.range);if(!match||(!match[1]&&!match[2])){res.writeHead(416,{...headers,'Content-Range':'bytes */'+size});return res.end();}if(match[1]){start=Number(match[1]);end=match[2]?Math.min(Number(match[2]),size-1):size-1;}else start=Math.max(0,size-Number(match[2]));if(!Number.isSafeInteger(start)||!Number.isSafeInteger(end)||start>=size||end<start){res.writeHead(416,{...headers,'Content-Range':'bytes */'+size});return res.end();}status=206;headers['Content-Range']=`bytes ${start}-${end}/${size}`;}
  headers['Content-Length']=end-start+1;res.writeHead(status,headers);if(req.method==='HEAD')return res.end();const stream=createReadStream(target,{start,end});stream.on('error',()=>res.destroy());res.on('close',()=>stream.destroy());stream.pipe(res);return;
 }

 const isHTML=path.extname(target)==='.html',route=new URL(req.url,'http://localhost').pathname,c=isHTML?{...config(),publicPreview:process.env.PUBLIC_PREVIEW==='1'}:null;
 const info=await stat(target),stamp=info.mtimeMs+':'+info.size+(isHTML?JSON.stringify(c):''),cacheKey=target+(isHTML?':'+route:'');let entry=staticCache.get(cacheKey);
 if(!entry||entry.stamp!==stamp){
  const promise=(async()=>{const source=await readFile(target),content=isHTML?Buffer.from(renderPublicHTML(source.toString('utf8'),route,c)):source,type=mimeTypes[path.extname(target)]||'application/octet-stream',gz=/^(text\/|image\/svg)/.test(type)&&content.length>1024?await compress(content):null;return {content,type,gz,hash:createHash('sha256').update(content).digest('hex').slice(0,24)};})();
  entry={stamp,promise};staticCache.set(cacheKey,entry);if(staticCache.size>100)staticCache.delete(staticCache.keys().next().value);
 }
 const asset=await entry.promise,useGzip=asset.gz&&/(?:^|,)\s*gzip(?:\s*;\s*q=(?!0(?:\.0*)?(?:\s|,|$))[0-9.]+)?(?:\s|,|$)/i.test(req.headers['accept-encoding']||''),etag='"'+asset.hash+(useGzip?'-gzip':'')+'"';
 const headers={'Content-Type':asset.type,'Cache-Control':target.includes(path.sep+'assets'+path.sep)?'public, max-age=300':'no-cache',ETag:etag,Vary:'Accept-Encoding'};
 if((req.headers['if-none-match']||'').split(',').map(v=>v.trim()).includes(etag)){res.writeHead(304,headers);return res.end();}
 const body=useGzip?asset.gz:asset.content;if(useGzip)headers['Content-Encoding']='gzip';headers['Content-Length']=body.length;
 res.writeHead(200,headers);res.end(req.method==='HEAD'?undefined:body);
}
const server=http.createServer(async(req,res)=>{secureHeaders(res);try{const url=new URL(req.url,'http://localhost');if(allowedPublicClient(req)){res.setHeader('Access-Control-Allow-Origin',process.env.PUBLIC_CLIENT_ORIGIN);res.setHeader('Vary','Origin');if(req.method==='OPTIONS'){res.writeHead(204,{'Access-Control-Allow-Methods':'GET, POST, OPTIONS','Access-Control-Allow-Headers':'Content-Type','Access-Control-Max-Age':'600'});return res.end();}}if(process.env.PUBLIC_PREVIEW==='1'&&(url.pathname==='/quan-tri'||url.pathname.startsWith('/api/admin/')))fail(403,'Cổng vận hành chỉ mở tại địa chỉ nội bộ của BOXANH.');if(url.pathname.startsWith('/api/'))return await api(req,res,url);if(req.method!=='GET'&&req.method!=='HEAD')fail(405,'Phương thức không được hỗ trợ.');let file=url.pathname==='/'?'/index.html':decodeURIComponent(url.pathname);if(!path.extname(file))file='/index.html';const target=path.resolve(ROOT,'public','.'+file),publicRoot=path.join(ROOT,'public');if(!target.startsWith(publicRoot+path.sep)||!existsSync(target))fail(404,'Không tìm thấy trang.');await serveStatic(req,res,target);}catch(error){if(!error.status)console.error('Request error:',error.message);if(!res.headersSent)json(res,{error:error.status?error.message:'BOXANH đang gặp lỗi. Thông tin của bạn vẫn được giữ trên biểu mẫu; vui lòng thử lại.'},error.status||500);else res.end();}});
server.requestTimeout=30000;server.headersTimeout=15000;
const port=Number(process.env.PORT||4173),host=process.env.HOST||'127.0.0.1';server.listen(port,host,()=>console.log(`BOXANH ready at http://${host}:${server.address().port}`));
process.on('SIGINT',()=>server.close(()=>{db.close();process.exit(0);}));
process.on('SIGTERM',()=>server.close(()=>{db.close();process.exit(0);}));
