import React, {useState} from 'react';
import {ArrowUpRight, ArrowRight, Truck, Package, MapPin, Check, Sparkles, KeyRound, ClipboardCheck, Recycle, BookOpen, Play, ShieldCheck, RotateCcw, Phone} from 'lucide-react';
import {QuickQuote, Confidence, Prices, Journey, Boxes, Surplus, Guides, FAQ} from './portal-home';

function Action({href,children,light=false}){return <a className={'v10-action '+(light?'v10-action-light':'')} href={href}>{children}<ArrowUpRight size={19}/></a>}
function Label({children}){return <p className="v10-label">{children}</p>}
export function MovingScene({c,onQuote}){return <>
  <section className="v10-moving"><div className="n7-wrap v10-moving-layout">
    <div className="v10-moving-copy"><Label>BOXANH / CHUYỂN TRỌ TẠI VINH</Label><h1>Đồ đạc đến nơi.<br/><em>Bạn đến khởi đầu mới.</em></h1><p>Giao hộp trước. Chuyển đồ đúng kế hoạch.<br/>Thu hồi hộp khi bạn đã sắp xếp xong.</p><Action href="/dat-lich?goi=full" light>Lên kế hoạch chuyển trọ</Action><a className="v10-underlink" href="/dich-vu#so-sanh">So sánh phạm vi các gói <ArrowRight size={16}/></a></div>
    <div className="v10-dispatch" aria-label="Minh họa kế hoạch chuyển trọ"><div className="v10-dispatch-head"><Truck size={25}/><span>HÀNH TRÌNH CỦA BẠN</span><span>VINH</span></div><div className="v10-address"><b>A</b><div><small>NƠI BẮT ĐẦU</small><strong>Phòng hiện tại</strong><span>Khảo sát · Giao hộp · Chuẩn bị</span></div></div><div className="v10-journey-line"><i/><span>Thống nhất quãng đường & điều kiện bốc xếp</span></div><div className="v10-address"><b>B</b><div><small>KHỞI ĐẦU MỚI</small><strong>Phòng mới của bạn</strong><span>Giao nhận · Kiểm đếm · Hẹn thu hộp</span></div></div><div className="v10-dispatch-foot"><Package size={18}/><span>Hộp dùng lại, theo từng lượt chuyển</span></div><small className="v10-demo-note">Sơ đồ quy trình · Chưa xác nhận lịch vận chuyển</small></div>
  </div><div className="n7-wrap v10-moving-bottom"><span><ClipboardCheck size={18}/> Khảo sát trước khi chốt</span><span><ShieldCheck size={18}/> Giao nhận có kiểm đếm</span><span><RotateCcw size={18}/> Thu hồi hộp theo lịch</span></div></section>
  <section className="n7-wrap v10-moving-story"><div><Label>MỘT PHÒNG TRỌ. NHIỀU VIỆC CẦN LO.</Label><h2>Gói việc cần làm<br/>vào một kế hoạch.</h2><p>Chọn phần việc phù hợp với bạn. Đồ cồng kềnh, cầu thang và hỗ trợ đóng gói được tách rõ khi khảo sát.</p><Action href="/huong-dan#checklist">Danh sách chuẩn bị</Action></div><figure><img src="/assets/moving.webp" alt="Ảnh tham khảo chuẩn bị đồ chuyển nơi ở" width="1200" height="800" loading="lazy"/><figcaption>Chuẩn bị gọn trước ngày chuyển · Ảnh tham khảo</figcaption></figure></section>
  <QuickQuote config={c} onQuote={onQuote}/><Journey/><Confidence/><div className="n7-wrap v10-crosslinks"><a href="/don-phong">Cần dọn phòng cũ?<ArrowRight size={18}/></a><a href="/ban-giao">Cần hỗ trợ bàn giao?<ArrowRight size={18}/></a></div>
</>}

const zones=[{name:'Phòng ở',icon:Package,copy:'Sàn, bề mặt, góc phòng và nội thất trong phạm vi đã khảo sát.',tasks:['Sàn & góc phòng','Bề mặt & nội thất','Thu gom theo thỏa thuận']},{name:'Bếp & vệ sinh',icon:Sparkles,copy:'Thống nhất trước mức độ bám bẩn, thiết bị và vật liệu cần xử lý.',tasks:['Bề mặt bếp','Khu vệ sinh','Vật liệu & chất tẩy phù hợp']},{name:'Phòng mới',icon:KeyRound,copy:'Dọn trước khi đưa đồ vào, theo tình trạng và lịch bạn mong muốn.',tasks:['Dọn trước khi chuyển đồ','Kiểm tra lại hiện trạng','Sẵn sàng cho ngày nhận phòng']}];
export function CleaningScene(){const [active,setActive]=useState(0);const zone=zones[active],Icon=zone.icon;return <>
  <section className="v10-cleaning"><div className="v10-cleaning-photo"><img src="/assets/room-real.webp" alt="Ảnh tham khảo căn phòng sáng và gọn gàng" width="900" height="1350"/><span>KHÔNG GIAN CHO MỘT KHỞI ĐẦU MỚI</span></div><div className="v10-cleaning-copy"><Label>BOXANH / CHĂM SÓC KHÔNG GIAN SỐNG</Label><h1>Không gian sạch.<br/><em>Tâm trí nhẹ.</em></h1><p>Dọn phòng cũ trước khi trả.<br/>Dọn phòng mới trước khi vào.</p><div className="v10-cleaning-note"><Sparkles size={26}/><span>Khảo sát hiện trạng<br/><strong>Chốt đúng hạng mục bạn cần</strong></span></div><Action href="/dat-lich?goi=cleaning">Đặt khảo sát dọn phòng</Action></div></section>
  <section className="n7-wrap v10-clean-scope"><div className="v10-clean-section-head"><Label>BẤM CHỌN KHU VỰC BẠN MUỐN DỌN</Label><h2>Sạch đúng chỗ bạn cần.</h2></div><div className="v10-clean-workspace"><div className="v10-clean-zone-list" role="tablist" aria-label="Khu vực cần dọn">{zones.map((z,i)=><button key={z.name} id={'v10-clean-tab-'+i} type="button" role="tab" aria-selected={active===i} aria-controls="v10-clean-panel" tabIndex={active===i?0:-1} onClick={()=>setActive(i)} onKeyDown={e=>{let next;if(['ArrowDown','ArrowRight'].includes(e.key))next=(i+1)%3;if(['ArrowUp','ArrowLeft'].includes(e.key))next=(i+2)%3;if(e.key==='Home')next=0;if(e.key==='End')next=2;if(next!==undefined){e.preventDefault();setActive(next);document.getElementById('v10-clean-tab-'+next)?.focus();}}}><span>0{i+1}</span><strong>{z.name}</strong><ArrowRight size={20}/></button>)}</div><div id="v10-clean-panel" role="tabpanel" aria-labelledby={'v10-clean-tab-'+active} className="v10-clean-panel"><Icon size={44}/><h3>{zone.name}</h3><p>{zone.copy}</p><div>{zone.tasks.map(t=><span key={t}><Check size={16}/>{t}</span>)}</div><small>Hạng mục cụ thể, vật tư, thời gian và phí được xác nhận sau khảo sát.</small></div></div></section>
  <section className="v10-clean-process"><div className="n7-wrap"><div><Label>TỪ HIỆN TRẠNG ĐẾN HOÀN TẤT</Label><h2>Ba bước.<br/>Một phòng sạch.</h2><p>Nấm mốc, côn trùng, chất thải đặc biệt và sửa chữa cần được khảo sát, xác nhận riêng.</p></div><ol>{[['Gửi ảnh hiện trạng','Địa chỉ, diện tích và ngày bạn muốn dọn.'],['Thống nhất hạng mục','BOXANH gửi phạm vi, vật tư và chi phí để bạn đồng ý.'],['Dọn & kiểm tra','Thực hiện theo phương án đã chốt, kiểm tra lại cùng khách.']].map(([t,d],i)=><li key={t}><b>0{i+1}</b><div><h3>{t}</h3><p>{d}</p></div></li>)}</ol></div></section><div className="n7-wrap v10-clean-footer"><h2>Để bạn nhẹ việc,<br/>phòng mới thêm dễ chịu.</h2><Action href="/dat-lich?goi=cleaning">Gửi yêu cầu dọn phòng</Action></div>
</>}

const inspection=['Ảnh hiện trạng phòng','Nội thất & vật dụng','Chỉ số điện, nước','Khoản cần đối soát','Chìa khóa & lịch bàn giao'];
export function HandoverScene(){const [checked,setChecked]=useState([]);return <>
  <section className="v10-handover n7-wrap"><div className="v10-handover-caption"><span><ClipboardCheck size={20}/> HỖ TRỢ BÀN GIAO PHÒNG</span><span>BOXANH / VINH, NGHỆ AN</span></div><div className="v10-handover-title"><h1>Khép lại chỗ cũ.<br/><em>Rõ ràng từng việc.</em></h1><div><p>Cùng kiểm tra phòng, đối chiếu vật dụng và ghi nhận bàn giao với chủ trọ.</p><Action href="/dat-lich?goi=handover">Hẹn khảo sát bàn giao</Action></div></div><div className="v10-inspection"><div className="v10-inspection-index"><KeyRound size={42}/><h2>Trước khi<br/>trả chìa khóa.</h2><p>Đánh dấu các phần bạn đã chuẩn bị.</p><span role="status">{checked.length} / {inspection.length} phần đã chuẩn bị</span><small>Danh sách cá nhân trên màn hình; chưa phải biên bản bàn giao.</small></div><div className="v10-inspection-list">{inspection.map((item,i)=><label key={item}><span>0{i+1}</span><strong>{item}</strong><input type="checkbox" checked={checked.includes(i)} onChange={()=>setChecked(checked.includes(i)?checked.filter(n=>n!==i):[...checked,i])}/></label>)}</div></div></section>
  <section className="v10-handover-notes n7-wrap"><article><Label>BẠN MANG THEO</Label><h2>Thông tin để đối chiếu.</h2><ul><li>Hợp đồng hoặc thỏa thuận thuê phòng</li><li>Danh sách đồ nhận khi vào ở</li><li>Ảnh hiện trạng và trao đổi liên quan</li><li>Thông tin điện, nước và lịch hẹn chủ trọ</li></ul></article><article><Label>BOXANH CÙNG BẠN</Label><h2>Kiểm tra và ghi nhận.</h2><ul><li>Chụp hiện trạng trước bàn giao</li><li>Đối chiếu nội thất, vật dụng và chỉ số</li><li>Ghi rõ hạng mục cần xử lý thêm</li><li>Xác nhận chìa khóa, ghi nhận bàn giao</li></ul></article><aside><ShieldCheck size={30}/><h3>Thống nhất rõ từ đầu.</h3><p>Dọn vệ sinh và sửa chữa nhỏ có thể đặt riêng sau khảo sát. Tiền thuê, tiền cọc do bạn và chủ trọ đối soát; BOXANH không cam kết hoàn trả tiền cọc.</p><Action href="/dat-lich?goi=handover">Gửi hiện trạng phòng</Action></aside></section>
</>}

const boxCycle=[['Nhận hộp','Giao theo lịch, cùng kiểm đếm số lượng và tình trạng.'],['Đóng & chuyển','Ghi nhóm đồ, giữ đồ quý bên mình, tuân thủ tải trọng được xác nhận.'],['Dỡ đồ','Sắp xếp tại phòng mới và hẹn ngày thu hồi.'],['Dùng tiếp','Kiểm tra, vệ sinh và đưa hộp đạt yêu cầu vào lượt tiếp theo.']];
export function BoxesScene(){const [stage,setStage]=useState(0);return <>
  <section className="v10-boxes"><div className="n7-wrap v10-box-layout"><div><Label>HỆ THỐNG HỘP TÁI SỬ DỤNG</Label><h1>Một chiếc hộp.<br/><em>Nhiều lần khởi đầu.</em></h1><p>Đóng đồ có trật tự. Chuyển cùng một hệ thống hộp.<br/>Dùng xong, BOXANH thu hồi để phục vụ lượt tiếp theo.</p><Action href="/dat-lich?goi=boxes">Nhận báo giá thuê hộp</Action><a className="v10-underlink" href="/hop-minh-hoa">Xem thẻ hộp minh họa <ArrowUpRight size={16}/></a></div><div className="v10-box-object"><span>BOXANH / CIRCULAR PACKAGING</span><img src="/assets/banner-moving.svg" alt="Hình minh họa chuyển đồ bằng hệ thống hộp" width="144" height="104"/><div><b>DÙNG LẠI</b><span>Nhận · Chuyển · Trả · Tiếp tục</span></div><small>Hình minh họa quy trình</small></div></div></section>
  <section className="n7-wrap v10-box-cycle"><div><Label>BẤM ĐỂ XEM TỪNG GIAI ĐOẠN</Label><h2>Vòng đời của hộp.<br/>Không dừng ở một chuyến.</h2></div><div className="v10-cycle-controls" aria-label="Vòng đời hộp">{boxCycle.map(([name],i)=><button type="button" aria-pressed={stage===i} key={name} onClick={()=>setStage(i)}><span>0{i+1}</span>{name}<ArrowRight size={17}/></button>)}</div><div className="v10-cycle-info" aria-live="polite"><Package size={32}/><div><h3>{boxCycle[stage][0]}</h3><p>{boxCycle[stage][1]}</p></div><strong>0{stage+1}<small>/ 04</small></strong></div></section><Boxes/><div className="n7-wrap v10-crosslinks"><a href="/dich-vu#hop">Tiêu chí, cách đóng & phí thuê<ArrowRight size={18}/></a><a href="/hop-minh-hoa">Mã hộp & tem niêm phong dự kiến<ArrowRight size={18}/></a></div>
</>}

const paths=[{title:'Thu mua',name:'buyback',intro:'Bạn nhường đồ. Nhận lại một phần giá trị.',copy:'Đồ được kiểm tra, thống nhất giá và tiếp nhận trước khi ghi nhận tiền thu mua hoặc giảm phí chuyến chuyển.',steps:['Gửi ảnh & tình trạng','Kiểm tra, thống nhất giá','Tiếp nhận & đối soát']},{title:'Ký gửi',name:'consign',intro:'Tìm người dùng mới cùng BOXANH.',copy:'Thống nhất giá bán, phí ký gửi, thời hạn và cách thanh toán. Khách nhận tiền sau khi món đồ đã bán và được đối soát.',steps:['Chốt điều kiện ký gửi','Tiếp nhận & đăng bán','Bán xong, đối soát']},{title:'Phân loại',name:'recycle',intro:'Đồ hỏng cũng cần một đầu ra phù hợp.',copy:'Phân loại theo vật liệu và tình trạng, xác nhận đối tác hoặc điểm thu gom phù hợp. BOXANH không tự nhận là cơ sở tái chế.',steps:['Ghi nhận nhóm đồ','Xác nhận đầu ra phù hợp','Thu gom theo thỏa thuận']}];
export function GreenScene(){const [mode,setMode]=useState(0);const item=paths[mode];return <>
  <section className="v10-green n7-wrap"><div className="v10-green-title"><Label>GIẢI PHÓNG ĐỒ THỪA</Label><h1>Bớt một món đồ.<br/><em>Thêm một vòng đời.</em></h1><p>Giữ thứ cần mang đi.<br/>Trao lại thứ còn giá trị.</p></div><figure><img src="/assets/books.jpg" width="400" height="300" alt="Sách minh họa việc trao lại đồ còn giá trị"/><figcaption><Recycle size={22}/> CÒN DÙNG ĐƯỢC, CÒN MỘT HÀNH TRÌNH</figcaption></figure><div className="v10-green-bottom"><span>Đồ của bạn</span><ArrowRight size={24}/><span>Giá trị mới</span><ArrowRight size={24}/><span>Người dùng tiếp theo</span></div></section>
  <section className="v10-green-paths"><div className="n7-wrap"><div className="v10-green-tabs" role="tablist" aria-label="Phương án cho đồ thừa">{paths.map((p,i)=><button key={p.name} id={'v10-green-tab-'+i} role="tab" aria-selected={mode===i} aria-controls="v10-green-panel" tabIndex={mode===i?0:-1} type="button" onClick={()=>setMode(i)} onKeyDown={e=>{let next;if(e.key==='ArrowRight')next=(i+1)%3;if(e.key==='ArrowLeft')next=(i+2)%3;if(e.key==='Home')next=0;if(e.key==='End')next=2;if(next!==undefined){e.preventDefault();setMode(next);document.getElementById('v10-green-tab-'+next)?.focus();}}}><span>0{i+1}</span>{p.title}<ArrowUpRight size={20}/></button>)}</div><div className="v10-green-panel" id="v10-green-panel" role="tabpanel" aria-labelledby={'v10-green-tab-'+mode}><div><Label>PHƯƠNG ÁN / {item.title.toUpperCase()}</Label><h2>{item.intro}</h2><p>{item.copy}</p><Action href={'/gui-do?phuong-an='+item.name}>Gửi đồ để {item.title.toLowerCase()}</Action></div><ol>{item.steps.map((s,i)=><li key={s}><b>0{i+1}</b><span>{s}</span><Check size={18}/></li>)}</ol></div></div></section><Surplus/><div className="n7-wrap v10-green-market"><div><Label>VÒNG ĐỜI MỚI</Label><h2>Biết đâu, bạn tìm thấy<br/>đồ mình đang cần.</h2><p>Chỉ món đã tiếp nhận, có ảnh thật và được công khai mới nhận yêu cầu quan tâm.</p></div><Action href="/do-cu">Khám phá danh mục đồ cũ</Action></div>
</>}

export function GuideScene({c,video,checklist}){return <><section className="v10-guide-intro n7-wrap"><div><Label>BOXANH / TRUNG TÂM HƯỚNG DẪN</Label><h1>Chuyển trọ lần đầu?<br/><em>Bắt đầu từ đây.</em></h1><p>Một video ngắn, danh sách chuẩn bị và câu trả lời cho những điều bạn đang băn khoăn.</p></div><BookOpen size={94} strokeWidth={1}/></section><div className="v10-guide-layout n7-wrap"><nav className="v10-guide-nav" aria-label="Mục lục hướng dẫn"><span>TRONG TRANG NÀY</span><a href="#video-huong-dan"><Play size={17}/> Xem cách dùng website<ArrowRight size={16}/></a><a href="#checklist"><ClipboardCheck size={17}/> Chuẩn bị ngày chuyển<ArrowRight size={16}/></a><a href="#cau-hoi"><BookOpen size={17}/> Câu hỏi thường gặp<ArrowRight size={16}/></a><Action href="/dat-lich">Bắt đầu yêu cầu</Action></nav><div className="v10-guide-content">{video}{checklist}</div></div><Guides/><FAQ config={c}/></>}

export function QuoteScene({c,onQuote}){return <><section className="v10-quote-intro n7-wrap" id="chi-phi"><div><Label>LẬP KẾ HOẠCH CHI PHÍ</Label><h1>Ước tính trước.<br/><em>Thống nhất sau khảo sát.</em></h1><p>Chọn dịch vụ, số hộp và quãng đường. Giá {c.priceMode==='reference'?'đang là mức dự kiến':'theo cấu hình hiện tại'}; BOXANH xác nhận phạm vi và tổng phí trước khi nhận lịch.</p></div><aside><ClipboardCheck size={24}/><strong>Biết chi phí.<br/>Chủ động quyết định.</strong><span>Gửi yêu cầu chưa xác nhận lịch và chưa yêu cầu thanh toán.</span></aside></section><QuickQuote config={c} onQuote={onQuote}/><Prices config={c}/><div className="n7-wrap v10-crosslinks"><a href="/dich-vu#so-sanh">Bảng so sánh đầy đủ<ArrowRight size={18}/></a><a href="/dich-vu#phu-phi">Phụ phí & điều kiện<ArrowRight size={18}/></a></div></>}
